<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>

    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
	  
    <AssemblyName>Timer</AssemblyName>
    <RootNamespace>Timer</RootNamespace>

    <!-- Produce a small, framework-dependent single-file executable -->
    <PublishSingleFile>true</PublishSingleFile>
    <SelfContained>false</SelfContained>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <PublishTrimmed>false</PublishTrimmed>
    <IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>

    <!-- Assembly metadata -->
    <Product>Timer</Product>
    <ApplicationIcon>Icons\timer_icon.ico</ApplicationIcon>

	<PublishSingleFile>true</PublishSingleFile>
	<RuntimeIdentifier>win-x64</RuntimeIdentifier>
  </PropertyGroup>

  <ItemGroup>
    <Resource Include="Icons\timer_icon.ico" />
    <Resource Include="Icons\*.png" />
    <Resource Remove="Icons\icon_finished.png" />
    <Resource Remove="Icons\ыфв.png" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Icons\*.png" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="PreserveNewest" />
    <Content Remove="Icons\icon_finished.png" />
    <Content Remove="Icons\ыфв.png" />
  </ItemGroup>

</Project>
